-- AGAPE (FRSC Cooperative) Contribution Tracker
-- Run this once in the Supabase SQL editor on a fresh project.
-- Safe to re-run: every statement is guarded with IF NOT EXISTS / OR REPLACE.

-- ---------------------------------------------------------------------------
-- 1. EXTENSIONS
-- ---------------------------------------------------------------------------
create extension if not exists "pgcrypto";

-- ---------------------------------------------------------------------------
-- 2. ENUMS
-- ---------------------------------------------------------------------------
do $$ begin
  create type deduction_category as enum ('savings', 'loan', 'electronic', 'other');
exception when duplicate_object then null; end $$;

do $$ begin
  create type member_status as enum ('active', 'inactive');
exception when duplicate_object then null; end $$;

do $$ begin
  create type app_role as enum ('admin', 'member');
exception when duplicate_object then null; end $$;

do $$ begin
  create type request_status as enum ('pending', 'accepted', 'declined');
exception when duplicate_object then null; end $$;

-- ---------------------------------------------------------------------------
-- 3. MEMBERS  (profiles, which reference members, is created right after)
-- ---------------------------------------------------------------------------
create table if not exists members (
  id               uuid primary key default gen_random_uuid(),
  coop_account_no  text not null unique,        -- e.g. ACS-002 — the durable identity
  name             text not null,
  bank_name        text,                        -- most recent bank seen for this member
  bank_account_no  text,                         -- most recent bank account seen
  email            text unique,                  -- login email, set when member account is created
  status           member_status not null default 'active',
  created_at       timestamptz not null default now(),
  updated_at       timestamptz not null default now()
);

create index if not exists idx_members_coop_account on members(coop_account_no);
create index if not exists idx_members_status on members(status);

-- ---------------------------------------------------------------------------
-- 5. PROFILES (real definition, now that members exists)
-- ---------------------------------------------------------------------------
create table if not exists profiles (
  id          uuid primary key references auth.users(id) on delete cascade,
  role        app_role not null default 'member',
  member_id   uuid references members(id) on delete set null,
  full_name   text,
  created_at  timestamptz not null default now()
);

-- ---------------------------------------------------------------------------
-- 6. MONTHLY IMPORTS  (one row per uploaded bank schedule file)
-- ---------------------------------------------------------------------------
create table if not exists monthly_imports (
  id               uuid primary key default gen_random_uuid(),
  import_key       text unique,                    -- stable idempotency key generated by the app
  bank_name        text not null,                -- 'UBA', 'FCMB', ...
  batch_label      text,                          -- e.g. 'BATCH I', 'BATCH II', null if n/a
  month            smallint not null check (month between 1 and 12),
  year             smallint not null check (year between 2000 and 2100),
  source_filename  text not null,
  row_count        integer not null default 0,
  mismatch_count   integer not null default 0,    -- rows where source TOTAL != recomputed sum
  uploaded_by      uuid references auth.users(id),
  uploaded_at      timestamptz not null default now()
);

alter table monthly_imports add column if not exists import_key text unique;
with keyed_imports as (
  select
    id,
    upper(btrim(bank_name)) || '|' ||
      year::text || '|' ||
      month::text || '|' ||
      upper(btrim(coalesce(batch_label, ''))) || '|' ||
      upper(btrim(source_filename)) as base_import_key
  from monthly_imports
  where import_key is null
),
ranked_imports as (
  select
    id,
    base_import_key,
    row_number() over (partition by base_import_key order by id) as duplicate_rank
  from keyed_imports
)
update monthly_imports mi
set import_key = case
  when ranked_imports.duplicate_rank = 1 then ranked_imports.base_import_key
  else ranked_imports.base_import_key || '|DUP' || ranked_imports.duplicate_rank::text
end
from ranked_imports
where mi.id = ranked_imports.id and mi.import_key is null;
create index if not exists idx_imports_month_year on monthly_imports(year, month);
create unique index if not exists idx_imports_import_key on monthly_imports(import_key);

-- ---------------------------------------------------------------------------
-- 7. DEDUCTION TRANSACTIONS  (append-only ledger — the source of truth)
--    One row per member, per category, per import. TOTAL is never stored;
--    it is always SUM(amount) across a member's 4 categories for a month.
-- ---------------------------------------------------------------------------
create table if not exists deduction_transactions (
  id          uuid primary key default gen_random_uuid(),
  member_id   uuid not null references members(id) on delete cascade,
  -- NULL import_id = a manual adjustment posted directly by an admin, not
  -- tied to a bank file. Postgres treats each NULL as distinct, so the
  -- unique constraint below still allows any number of manual adjustments
  -- per member/category (it only dedupes rows from the SAME import).
  import_id   uuid references monthly_imports(id) on delete cascade,
  month       smallint not null check (month between 1 and 12),
  year        smallint not null check (year between 2000 and 2100),
  category    deduction_category not null,
  amount      numeric(14,2) not null default 0,   -- positive = credit/deduction added, negative = manual reversal
  source_name text,                                -- name as printed on the imported schedule row
  source_coop_account_no text,                     -- coop account number as printed on the imported schedule row
  source_bank_name text,                           -- bank selected for this import row
  source_bank_account_no text,                     -- bank account number as printed on the imported schedule row
  source_sheet_name text,                          -- worksheet the imported row came from
  note        text,
  created_by  uuid references auth.users(id),
  created_at  timestamptz not null default now(),
  -- one row per member+import+category — re-importing the same file updates, not duplicates
  unique (member_id, import_id, category)
);

alter table deduction_transactions add column if not exists source_name text;
alter table deduction_transactions add column if not exists source_coop_account_no text;
alter table deduction_transactions add column if not exists source_bank_name text;
alter table deduction_transactions add column if not exists source_bank_account_no text;
alter table deduction_transactions add column if not exists source_sheet_name text;
create index if not exists idx_txn_member on deduction_transactions(member_id);
create index if not exists idx_txn_month_year on deduction_transactions(year, month);
create index if not exists idx_txn_import on deduction_transactions(import_id);

-- ---------------------------------------------------------------------------
-- 8. BALANCES  (derived cache, kept in sync by trigger — never edit directly)
-- ---------------------------------------------------------------------------
create table if not exists balances (
  member_id        uuid not null references members(id) on delete cascade,
  category         deduction_category not null,
  running_balance  numeric(14,2) not null default 0,
  updated_at       timestamptz not null default now(),
  primary key (member_id, category)
);

-- Balance convention: all imported deductions accumulate by category.
-- "loan" therefore means loan repaid to date unless you add separate
-- principal/disbursement tracking later.
create or replace function recompute_balance(p_member_id uuid, p_category deduction_category)
returns void language plpgsql as $$
declare
  v_sum numeric(14,2);
begin
  select coalesce(sum(amount), 0) into v_sum
  from deduction_transactions
  where member_id = p_member_id and category = p_category;

  insert into balances (member_id, category, running_balance, updated_at)
  values (p_member_id, p_category, v_sum, now())
  on conflict (member_id, category)
  do update set running_balance = excluded.running_balance, updated_at = now();
end;
$$;

create or replace function trg_deduction_transactions_balance()
returns trigger language plpgsql as $$
begin
  if (tg_op = 'DELETE') then
    perform recompute_balance(old.member_id, old.category);
    return old;
  else
    perform recompute_balance(new.member_id, new.category);
    if (tg_op = 'UPDATE' and (old.member_id != new.member_id or old.category != new.category)) then
      perform recompute_balance(old.member_id, old.category);
    end if;
    return new;
  end if;
end;
$$;

drop trigger if exists on_deduction_transactions_change on deduction_transactions;
create trigger on_deduction_transactions_change
after insert or update or delete on deduction_transactions
for each row execute function trg_deduction_transactions_balance();

-- ---------------------------------------------------------------------------
-- 9. updated_at helper for members
-- ---------------------------------------------------------------------------
create or replace function set_updated_at()
returns trigger language plpgsql as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

drop trigger if exists on_members_update on members;
create trigger on_members_update
before update on members
for each row execute function set_updated_at();

-- ---------------------------------------------------------------------------
-- 10. Convenience view: per-member per-month total (what the UI shows)
-- ---------------------------------------------------------------------------
create or replace view member_month_totals as
select
  t.member_id,
  m.coop_account_no,
  m.name,
  t.year,
  t.month,
  sum(t.amount) filter (where t.category = 'savings')    as savings,
  sum(t.amount) filter (where t.category = 'loan')        as loan,
  sum(t.amount) filter (where t.category = 'electronic')  as electronic,
  sum(t.amount) filter (where t.category = 'other')       as other,
  sum(t.amount)                                           as total
from deduction_transactions t
join members m on m.id = t.member_id
group by t.member_id, m.coop_account_no, m.name, t.year, t.month;

-- ---------------------------------------------------------------------------
-- 11. ROW LEVEL SECURITY
-- ---------------------------------------------------------------------------
alter table members enable row level security;
alter table profiles enable row level security;
alter table monthly_imports enable row level security;
alter table deduction_transactions enable row level security;
alter table balances enable row level security;

-- helper: is the current user an admin?
create or replace function is_admin()
returns boolean language sql stable as $$
  select exists (
    select 1 from profiles where id = auth.uid() and role = 'admin'
  );
$$;

-- profiles: users can read their own profile; admins can read all
drop policy if exists profiles_select on profiles;
create policy profiles_select on profiles for select
  using (id = auth.uid() or is_admin());

drop policy if exists profiles_admin_write on profiles;
create policy profiles_admin_write on profiles for all
  using (is_admin()) with check (is_admin());

-- members: a member can read only their own row; admins read/write all
drop policy if exists members_select_own on members;
create policy members_select_own on members for select
  using (
    is_admin()
    or id = (select member_id from profiles where id = auth.uid())
  );

drop policy if exists members_admin_write on members;
create policy members_admin_write on members for all
  using (is_admin()) with check (is_admin());

-- monthly_imports: admin only (members never need to see raw import batches)
drop policy if exists imports_admin_only on monthly_imports;
create policy imports_admin_only on monthly_imports for all
  using (is_admin()) with check (is_admin());

-- deduction_transactions: member sees only their own; admin sees/writes all
drop policy if exists txn_select_own on deduction_transactions;
create policy txn_select_own on deduction_transactions for select
  using (
    is_admin()
    or member_id = (select member_id from profiles where id = auth.uid())
  );

drop policy if exists txn_admin_write on deduction_transactions;
create policy txn_admin_write on deduction_transactions for all
  using (is_admin()) with check (is_admin());

-- balances: same shape as transactions
drop policy if exists balances_select_own on balances;
create policy balances_select_own on balances for select
  using (
    is_admin()
    or member_id = (select member_id from profiles where id = auth.uid())
  );

drop policy if exists balances_admin_write on balances;
create policy balances_admin_write on balances for all
  using (is_admin()) with check (is_admin());

-- ---------------------------------------------------------------------------
-- 12. MEMBERSHIP REQUESTS
--     A member signs up (creating an auth.users login) and submits one of
--     these with the name/account number they claim. Nothing links their
--     login to a member record until an admin accepts it.
-- ---------------------------------------------------------------------------
create table if not exists membership_requests (
  id               uuid primary key default gen_random_uuid(),
  auth_user_id     uuid not null unique references auth.users(id) on delete cascade,
  name             text not null,
  email            text not null,
  coop_account_no  text not null,
  status           request_status not null default 'pending',
  member_id        uuid references members(id) on delete set null, -- set once accepted
  created_at       timestamptz not null default now(),
  reviewed_at      timestamptz,
  reviewed_by      uuid references auth.users(id)
);

create index if not exists idx_requests_status on membership_requests(status);

alter table membership_requests enable row level security;

-- a signed-in user can see (and re-submit) only their own request; admin sees all
drop policy if exists requests_select_own on membership_requests;
create policy requests_select_own on membership_requests for select
  using (auth_user_id = auth.uid() or is_admin());

drop policy if exists requests_admin_write on membership_requests;
create policy requests_admin_write on membership_requests for all
  using (is_admin()) with check (is_admin());

-- ---------------------------------------------------------------------------
-- 13. First admin bootstrap
--     After your first admin signs up through Supabase Auth, run:
--     insert into profiles (id, role, full_name)
--     values ('<their auth.users.id>', 'admin', 'Full Name')
--     on conflict (id) do update set role = 'admin';
-- ---------------------------------------------------------------------------
